### ISSUE TITLE
Symfony 7 Support

### ISSUE THREAD

**Issue by anthonylex** [jbtronics/2fa-webauthn#1]
Hey, you have upgraded the composer to work with symfony/framework-bundle version 7.0 but not the symfomny/uid:
<img width="376" alt="image" src="https://github.com/jbtronics/2fa-webauthn/assets/140404418/8005a4ce-09ed-4179-b402-e13c358607cd">

Is there any reason why this hasn't been done?

**Comment by jbtronics** [comment]
I just forget to allow it there too. There are no changes between symfony/uid 6.4 and 7.0

With the new 2.2.1 release this should be allowed too.
