### ISSUE TITLE
symfony/psr-http-message-bridge 2.1

### ISSUE THREAD

**Issue by Jake-Intermotor** [jbtronics/2fa-webauthn#2]
Hello!

Thanks for the package! Currently can't install though as the composer.json says it needs symfony/psr-http-message-bridge ^2.1 and composer blocks the install as i have v7.1.1 installed. 

Any reason we can't bump the version on that package?

Thanks! :D

**Comment by Jake-Intermotor** [comment]
![Screenshot 2024-07-18 at 16 41 24](https://github.com/user-attachments/assets/dd8e3858-1b5d-4439-941c-56cdb5d7d66b)

**Comment by jbtronics** [comment]
I think it should work with the newer versions too, at least the changelog contains nothing which should break the usage in this bundle.

With the release of Symfony 6.4 the version schema of this package was changed and now follows these of symfony. (Before you could use the 2.* versions for all symfony versions).

**Comment by jbtronics** [comment]
Fixed with version 2.2.2

**Comment by Jake-Intermotor** [comment]
Perfect! Installs fine now, thank you!
